services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: weather_ai_api
    ports:
      - '3000:3000'
    restart: always
    env_file:
      - .env
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: weather_ai_web
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOSTNAME=0.0.0.0
    depends_on:
      - api
    ports:
      - '3001:3001'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
